version: "3"

networks:
  project2_network:
    driver: bridge
    name: project2_network


services:

  stream_emulator:
    build: 
      context: ./event-producer
    container_name: event-producer
    networks:
      - project2_network
    depends_on:
      - kafka
    tty : true
    volumes:
      - ../src/monitoring-events:/home/kafka-producer/src
      - ../dataset:/home/kafka-producer/dataset


  results_consumer:
    build:
      context: ./results-consumer
    container_name: consumer-csv
    networks:
      - project2_network
    depends_on:
      - kafka
    tty : true
    volumes:
      - ../Results:/home/consumer-csv/results
      - ../src/results-consumer:/home/consumer-csv/src
    working_dir: /home/consumer-csv
    command: bash -c " sleep 5; python src/main.py"



  faust_preprocessing:
    build:
      context: ./faust
    networks:
      - project2_network
    depends_on:
      - kafka
    tty : true
    volumes:
      - ../src/faust-preprocessing:/home/faust/src
    
    
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    hostname: kafka-broker
    networks:
      - project2_network
    ports:
      - 9092:9092
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=2


  jobmanager:
    build:
      context: ./flink
    networks:
      - project2_network
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
    depends_on:
      - kafka
    tty: true


  taskmanager:
    build:
      context: ./flink
    networks:
      - project2_network
    depends_on:
      - jobmanager
    volumes:
      - ../src/processing:/opt/flink/job
    working_dir: /opt/flink/job
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
        metrics.latency.interval: 1000
    tty: true 


  prometheus:
    image: prom/prometheus
    ports:
      - 9010:9010
      - 9090:9090
    networks:
      - project2_network
    tty: true
    volumes:
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus/data


  grafana :
    image: grafana/grafana
    networks:
      - project2_network
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - auth.anonymous.enabled=true
      - auth.anonymous.org_role = Admin
    tty : true