{
 "title": "Flink Metrics",
 "time": { "from": "now-25m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query 1 Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query1_day\", quantile=\"0.999\"})",
     "legendFormat": "1 Day"
    },
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query1_3days\", quantile=\"0.999\"})",
     "legendFormat": "3 Days"
    },
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query1_alldays\", quantile=\"0.99\"})",
     "legendFormat": "All Days"
    }
   ]
  },
  {
   "title": "Query 2 Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query2_day\", quantile=\"0.999\"})",
     "legendFormat": "1 Day"
    },
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query2_3days\", quantile=\"0.999\"})",
     "legendFormat": "3 Days"
    },
    {
     "expr": "max(flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_name=\"query2_alldays\", quantile=\"0.999\"})",
     "legendFormat": "All Days"
    }
   ]
  },
  {
   "title": "Query 1 Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query1_day\"})",
     "legendFormat": "1 Day"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query1_3days\"})",
     "legendFormat": "3 Days"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query1_alldays\"})",
     "legendFormat": "All Days"
    }
   ]
  },
  {
   "title": "Query 2 Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query2_day\"})",
     "legendFormat": "1 Day"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query2_3days\"})",
     "legendFormat": "3 Days"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=\"query2_alldays\"})",
     "legendFormat": "All Days"
    }
   ]
  }
 ]
}